name: Deploy demo

on:
  push:
    paths:
      - demo/**/*
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install & build
        run: |
          npm ci
          npm run build
      - name: Install & build demo
        run: |
          cd demo
          npm ci
          npx connect-deps link .. -c
          npm run build
          npm run export
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_DIR: demo/out
          PUBLISH_BRANCH: gh-pages
